### ISSUE TITLE
Updating X-Project

### ISSUE THREAD

**Issue by profucius** [stooged/xPloitServer#1]
Hi there, great software. Curious, is there a way that we can update the X-Project version when they release newer versions? Today version 1.5.5 was released, I would like to update xPloitServer to run this, can I do this myself?

https://www.psxhax.com/threads/x-project-1-5-5-by-defaultdnb-leeful.6616/

**Comment by stooged** [comment]
to update the files on the device/phone plug it into a computer and find the **xPloitServer** folder and copy paste the new xproject files into that folder overwriting all files.


if you are compiling the android project the x-project files are in a zip that is in the res/raw folder
https://github.com/stooged/xPloitServer/tree/master/res/raw
it is named **xproject_zip**
